### ISSUE TITLE
How to set heat delta

### ISSUE THREAD

**Issue by Joeknx** [Egyras/HeishaMon#227]
I was wondering how i could set heat delta TOP23.
If i try SET18 SetFloorHeatDelta nothing changes.

Monoblock J-Geisha 5kW

Thanks!

**Comment by MiG-41** [comment]
Just checked, SetFloorHeatDelta set correct TOP23. 
Maybe ou can usu the newest fw : https://github.com/IgorYbema/HeishaMon/blob/main/binaries/HeishaMon.ino.d1-v2.1-iy-10.bin

**Comment by Joeknx** [comment]
Ok thx!
I already have 2.1-iy4 but i will try the newest one.

**Comment by Joeknx** [comment]
I work with Openhab3. I had a Channel for "Heat Delta". The additional set command "SetFloorHeatDelta" did not work there.
With an extra Channel just von the set command it works!
