### ISSUE TITLE
SetDHWHeatDelta sets floor delta

### ISSUE THREAD

**Issue by emign** [Egyras/HeishaMon#228]
Hi,

when I send `3` to `panasonic_heat_pump/commands/SetDHWHeatDelta`
the console logs: 

> set floor heat delta to 3
sent bytes: 111 including checksum value: 15 
Received 203 bytes data
Checksum and header received ok!
received TOP1 Pump_Flow: 11.59
received TOP22 DHW_Heat_Delta: 3

**Comment by MiG-41** [comment]
Floor Delta is TOP23 ... 
Here everything looks ok.
EDIT: But looks like yuo should send only negative nummbers ( so -3) , not positive...

**Comment by trsqr** [comment]
@MiG-41 the console log says "set **floor** heat delta to 3" even if the command used is "Set**DHW**HeatDelta". I guess there's a mismatch (I know it's only a printout, but anyhow)?

**Comment by MiG-41** [comment]
ah , ok  ,only console lies :)

**Comment by emign** [comment]
Yes. So to say. I was puzzled because there were no changes made on the HP side after the command (DHW and floor delta stayed the same). I then realized it was in DHW mode. The changes are correctly applied when it is NOT currently in DHW mode 

BTW: the topic docu states only values 0-15 are allowed. I cannot send negative values

**Comment by emign** [comment]
aah. It only accepts negative values. The Doc is wrong

**Comment by IgorYbema** [comment]
https://github.com/Egyras/HeishaMon/blob/master/HeishaMon/commands.cpp#L481 should be changed indeed. I'll fix that.

Also,, 
SET20 | SetDHWHeatDelta | Set DHW heating delta in Kelvin | 1-15
Should indeed be changed to -15 / -1

**Comment by IgorYbema** [comment]
Fixed in https://github.com/IgorYbema/HeishaMon/commit/8c1b41723b73e7124f0516bca1b21f304455339d

**Comment by trsqr** [comment]
Just a question, is the SET18 using also negative numbers?

**Comment by MiG-41** [comment]
No , SET18 use positive , only DHW delta is negative , ask Panasonic why....

**Comment by MiG-41** [comment]
> Also,,
> SET20 | SetDHWHeatDelta | Set DHW heating delta in Kelvin | 1-15
> Should indeed be changed to -15 / -1

@IgorYbema Wrote to you on Slack...
Some time ago it was agreed , that Heishamon will be using booth ,positive and negative values ( it will be doing negative internally ) ,and description should stay ,but looks like this change was forgotten. Maybe come back to that idea ?

**Comment by IgorYbema** [comment]
No we don't do l logic in the heishamon. If the data from the heatpump says 'negative' the set command should be 'negative' also.
