### ISSUE TITLE
Support for buffer tank delta T setter and getter

### ISSUE THREAD

**Issue by burt2902** [Egyras/HeishaMon#339]
I would find it very helpful if buffer tank delta T could be read and modified via HeishaMon. Can this setting get exposed?

Some reasoning...
The current logic of Aquarea pumps is broken when it comes to handling buffer tank delta T. Assuming that the heating target water temperature is X deg C and buffer tank delta T is set to any value between 1 and 10, the pump will charge the buffer tank to X+delta T+2 deg C, then it will go idle and start charging again when the temperature in the tank drops either to X+1 or by 6 deg.
Considering that, setting delta T to anything above 6 deg does not make much sense and only increases power consumption. Being able to temporarily set delta T to 10 while charging the tank and that back to 6 when discharging it would make both the work and break cycles longer.

**Comment by geduxas** [comment]
In latest firmware it is implemented allready. TOP113, and  SET27

**Comment by burt2902** [comment]
Great news! Time to update the firmware then...

**Comment by burt2902** [comment]
Just updated to v3.1 and both are available. Closing...
